# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
jobs:
  - name: cronjob
    image:
      repository: ubuntu
      tag: latest
      pullPolicy: Always
    schedule: "* * * * *"
    command: ["/bin/echo"]
    args:
      - "i am a cronjob"
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Forbid
