# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
jobs:
  - name: hello-world
    image:
      repository: hello-world
      tag: latest
      pullPolicy: IfNotPresent
    schedule: "* * * * *"
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Allow
  - name: hello-ubuntu
    image:
      repository: ubuntu
      tag: latest
      pullPolicy: Always
    schedule: "*/5 * * * *"
    command: ["/bin/bash"]
    args:
      - "-c"
      - "echo $(date) - hello from ubuntu"
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Forbid
  - name: hello-env-var
    image:
      repository: busybox
      tag: latest
      pullPolicy: Always
    # optional env vars
    env:
    - name: ECHO_VAR
      value: "busybox"
    schedule: "* * * * *"
    command: ["/bin/sh"]
    args:
      - "-c"
      - "echo $(date) - hello from $ECHO_VAR"
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Forbid
